# Generated by Django 5.2.17 on 2026-08-18 06:14

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicfile',
            name='file',
            field=models.FileField(upload_to=core.models.upload_public_file),
        ),
        migrations.AlterField(
            model_name='publicfile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
