# Generated by Django 5.2.17 on 2026-09-21 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicFileFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.publicfilefolder')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='core.publicfileproject')),
            ],
        ),
        migrations.AddField(
            model_name='publicfile',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='core.publicfilefolder'),
        ),
        migrations.AddConstraint(
            model_name='publicfilefolder',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('project', 'parent', 'slug'), name='unique_folder_slug_per_parent'),
        ),
        migrations.AddConstraint(
            model_name='publicfilefolder',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('project', 'slug'), name='unique_root_folder_slug_per_project'),
        ),
    ]
