# Generated by Django 5.2.17 on 2026-08-29 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('logo', models.URLField(blank=True, max_length=1000)),
                ('url', models.URLField(max_length=1000, verbose_name='URL de streaming')),
                ('use_hls', models.BooleanField(default=False, verbose_name='Usa HLS')),
                ('link_direct', models.BooleanField(default=False, verbose_name='Link directo')),
                ('language', models.CharField(default='es', max_length=10, verbose_name='Idioma')),
                ('country', models.CharField(default='AR', max_length=10, verbose_name='País')),
                ('category', models.CharField(default='General', max_length=255, verbose_name='Categoría')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Es Premium')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('rating', models.FloatField(blank=True, null=True, verbose_name='Rating')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Orden')),
                ('headers', models.JSONField(blank=True, default=dict, verbose_name='Headers')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(default='IPTV/ORG', max_length=255, verbose_name='Fuente')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duración (min)')),
                ('poster', models.URLField(blank=True, verbose_name='Poster')),
                ('backdrop', models.URLField(blank=True, verbose_name='Backdrop')),
                ('trailer_url', models.URLField(blank=True, verbose_name='Trailer')),
                ('stream_url', models.URLField(blank=True, null=True, verbose_name='URL de reproducción')),
                ('is_hls', models.BooleanField(default=True, verbose_name='Es HLS')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('external_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('source_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='channel.channel')),
            ],
        ),
    ]
