# Generated by Django 5.2.17 on 2026-10-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='playback_type',
            field=models.CharField(choices=[('native', 'Native'), ('youtube', 'YouTube')], default='native', max_length=16, verbose_name='Reproductor'),
        ),
    ]
